-- Clarys - esquema inicial Supabase
-- Pegar completo en Supabase SQL Editor y ejecutar una sola vez.

create extension if not exists pgcrypto;

create table if not exists public.workshops (
    id uuid primary key default gen_random_uuid(),
    owner_user_id uuid not null unique references auth.users(id) on delete cascade,
    name text not null,
    whatsapp text,
    currency text not null default 'COP',
    default_min_stock integer not null default 5,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    workshop_id uuid not null references public.workshops(id) on delete cascade,
    role text not null check (role in ('admin', 'seller', 'customer')),
    created_at timestamptz not null default now()
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    workshop_id uuid not null references public.workshops(id) on delete cascade,
    name text not null,
    description text,
    category text,
    purchase_price integer not null default 0,
    sale_price integer not null default 0,
    stock integer not null default 0 check (stock >= 0),
    min_stock integer not null default 0 check (min_stock >= 0),
    sizes text,
    colors text,
    sku text,
    image_url text,
    active boolean not null default true,
    sold_units integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.customers (
    id bigint generated by default as identity primary key,
    workshop_id uuid not null references public.workshops(id) on delete cascade,
    name text not null,
    phone text,
    total_orders integer not null default 0,
    total_spent integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.sales (
    id bigint generated by default as identity primary key,
    workshop_id uuid not null references public.workshops(id) on delete cascade,
    customer_id bigint references public.customers(id) on delete set null,
    payment_method text not null default 'Pendiente',
    status text not null default 'Confirmada',
    discount integer not null default 0,
    total integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references public.sales(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete restrict,
    quantity integer not null check (quantity > 0),
    unit_price integer not null default 0,
    subtotal integer not null default 0
);

create table if not exists public.inventory_movements (
    id bigint generated by default as identity primary key,
    workshop_id uuid not null references public.workshops(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete cascade,
    movement_type text not null check (movement_type in ('Entrada', 'Salida', 'Ajuste')),
    quantity integer not null check (quantity > 0),
    previous_stock integer not null default 0,
    new_stock integer not null default 0,
    reason text,
    created_at timestamptz not null default now()
);

create table if not exists public.contact_requests (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    customer_phone text,
    items jsonb not null default '[]'::jsonb,
    ai_description text,
    status text not null default 'new',
    created_at timestamptz not null default now()
);

create or replace function public.current_workshop_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
    select p.workshop_id
    from public.profiles p
    where p.user_id = auth.uid()
    limit 1;
$$;

alter table public.workshops enable row level security;
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.contact_requests enable row level security;

drop policy if exists "public can view active workshops" on public.workshops;
create policy "public can view active workshops"
on public.workshops for select
using (is_active = true);

drop policy if exists "owners can insert own workshop" on public.workshops;
create policy "owners can insert own workshop"
on public.workshops for insert
with check (owner_user_id = auth.uid());

drop policy if exists "owners can update own workshop" on public.workshops;
create policy "owners can update own workshop"
on public.workshops for update
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());

drop policy if exists "users can view own profile" on public.profiles;
create policy "users can view own profile"
on public.profiles for select
using (user_id = auth.uid());

drop policy if exists "users can insert own admin profile" on public.profiles;
create policy "users can insert own admin profile"
on public.profiles for insert
with check (user_id = auth.uid() and role = 'admin');

drop policy if exists "public can view active products" on public.products;
create policy "public can view active products"
on public.products for select
using (active = true);

drop policy if exists "admins can view own products" on public.products;
create policy "admins can view own products"
on public.products for select
using (workshop_id = public.current_workshop_id());

drop policy if exists "admins can insert own products" on public.products;
create policy "admins can insert own products"
on public.products for insert
with check (workshop_id = public.current_workshop_id());

drop policy if exists "admins can update own products" on public.products;
create policy "admins can update own products"
on public.products for update
using (workshop_id = public.current_workshop_id())
with check (workshop_id = public.current_workshop_id());

drop policy if exists "admins can delete own products" on public.products;
create policy "admins can delete own products"
on public.products for delete
using (workshop_id = public.current_workshop_id());

drop policy if exists "admins can manage own customers" on public.customers;
create policy "admins can manage own customers"
on public.customers for all
using (workshop_id = public.current_workshop_id())
with check (workshop_id = public.current_workshop_id());

drop policy if exists "admins can manage own sales" on public.sales;
create policy "admins can manage own sales"
on public.sales for all
using (workshop_id = public.current_workshop_id())
with check (workshop_id = public.current_workshop_id());

drop policy if exists "admins can view own sale items" on public.sale_items;
create policy "admins can view own sale items"
on public.sale_items for select
using (
    exists (
        select 1 from public.sales s
        where s.id = sale_id
        and s.workshop_id = public.current_workshop_id()
    )
);

drop policy if exists "admins can insert own sale items" on public.sale_items;
create policy "admins can insert own sale items"
on public.sale_items for insert
with check (
    exists (
        select 1 from public.sales s
        where s.id = sale_id
        and s.workshop_id = public.current_workshop_id()
    )
);

drop policy if exists "admins can manage own inventory movements" on public.inventory_movements;
create policy "admins can manage own inventory movements"
on public.inventory_movements for all
using (workshop_id = public.current_workshop_id())
with check (workshop_id = public.current_workshop_id());

drop policy if exists "public can create contact requests" on public.contact_requests;
create policy "public can create contact requests"
on public.contact_requests for insert
with check (true);

create or replace function public.adjust_stock(
    p_product_id bigint,
    p_movement_type text,
    p_quantity integer,
    p_reason text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_workshop_id uuid := public.current_workshop_id();
    v_previous integer;
    v_new integer;
begin
    if v_workshop_id is null then
        raise exception 'Usuario sin taller';
    end if;

    select stock into v_previous
    from public.products
    where id = p_product_id and workshop_id = v_workshop_id
    for update;

    if v_previous is null then
        raise exception 'Producto no encontrado';
    end if;

    if p_quantity <= 0 then
        raise exception 'Cantidad invalida';
    end if;

    if p_movement_type = 'Entrada' then
        v_new := v_previous + p_quantity;
    elsif p_movement_type = 'Salida' then
        v_new := greatest(0, v_previous - p_quantity);
    elsif p_movement_type = 'Ajuste' then
        v_new := p_quantity;
    else
        raise exception 'Tipo de movimiento invalido';
    end if;

    update public.products
    set stock = v_new, updated_at = now()
    where id = p_product_id and workshop_id = v_workshop_id;

    insert into public.inventory_movements (
        workshop_id, product_id, movement_type, quantity, previous_stock, new_stock, reason
    ) values (
        v_workshop_id, p_product_id, p_movement_type, p_quantity, v_previous, v_new, p_reason
    );
end;
$$;

create or replace function public.confirm_sale(
    p_customer_name text,
    p_customer_phone text,
    p_payment_method text,
    p_discount integer,
    p_status text,
    p_items jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_workshop_id uuid := public.current_workshop_id();
    v_customer_id bigint;
    v_sale_id bigint;
    v_item jsonb;
    v_product_id bigint;
    v_quantity integer;
    v_unit_price integer;
    v_previous integer;
    v_total integer := 0;
begin
    if v_workshop_id is null then
        raise exception 'Usuario sin taller';
    end if;

    if jsonb_array_length(p_items) = 0 then
        raise exception 'La venta no tiene productos';
    end if;

    insert into public.customers (workshop_id, name, phone, total_orders, total_spent)
    values (v_workshop_id, coalesce(nullif(p_customer_name, ''), 'Cliente mostrador'), p_customer_phone, 0, 0)
    returning id into v_customer_id;

    insert into public.sales (workshop_id, customer_id, payment_method, status, discount, total)
    values (v_workshop_id, v_customer_id, p_payment_method, p_status, greatest(0, p_discount), 0)
    returning id into v_sale_id;

    for v_item in select * from jsonb_array_elements(p_items)
    loop
        v_product_id := (v_item->>'product_id')::bigint;
        v_quantity := (v_item->>'quantity')::integer;

        if v_quantity <= 0 then
            raise exception 'Cantidad invalida';
        end if;

        select stock, sale_price into v_previous, v_unit_price
        from public.products
        where id = v_product_id and workshop_id = v_workshop_id and active = true
        for update;

        if v_previous is null then
            raise exception 'Producto no encontrado';
        end if;

        if v_previous < v_quantity then
            raise exception 'Stock insuficiente';
        end if;

        insert into public.sale_items (sale_id, product_id, quantity, unit_price, subtotal)
        values (v_sale_id, v_product_id, v_quantity, v_unit_price, v_unit_price * v_quantity);

        update public.products
        set stock = stock - v_quantity,
            sold_units = sold_units + v_quantity,
            updated_at = now()
        where id = v_product_id and workshop_id = v_workshop_id;

        insert into public.inventory_movements (
            workshop_id, product_id, movement_type, quantity, previous_stock, new_stock, reason
        ) values (
            v_workshop_id, v_product_id, 'Salida', v_quantity, v_previous, v_previous - v_quantity,
            'Venta #' || v_sale_id
        );

        v_total := v_total + (v_unit_price * v_quantity);
    end loop;

    v_total := greatest(0, v_total - greatest(0, p_discount));

    update public.sales
    set total = v_total
    where id = v_sale_id;

    update public.customers
    set total_orders = total_orders + 1,
        total_spent = total_spent + v_total
    where id = v_customer_id;

    return v_sale_id;
end;
$$;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "public can view product images" on storage.objects;
create policy "public can view product images"
on storage.objects for select
using (bucket_id = 'product-images');

drop policy if exists "authenticated can upload product images" on storage.objects;
create policy "authenticated can upload product images"
on storage.objects for insert
with check (bucket_id = 'product-images' and auth.role() = 'authenticated');

drop policy if exists "authenticated can update product images" on storage.objects;
create policy "authenticated can update product images"
on storage.objects for update
using (bucket_id = 'product-images' and auth.role() = 'authenticated')
with check (bucket_id = 'product-images' and auth.role() = 'authenticated');

drop policy if exists "authenticated can delete product images" on storage.objects;
create policy "authenticated can delete product images"
on storage.objects for delete
using (bucket_id = 'product-images' and auth.role() = 'authenticated');
